Description: >
    Sadrayan Jenkins Host

Parameters:
    EnvironmentName:
      Description: An environment name that will be prefixed to resource names
      Type: String
      Default: "Capston-Project"

Resources:
  JenkinsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name 
          Value: Jenkins-SG
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: "${EnvironmentName}-VPCID"

  JenkinsHost:
    Type: AWS::EC2::Instance
    Properties: 
      BlockDeviceMappings: 
        - DeviceName: "/dev/xvda"
          Ebs: 
            VolumeType: "gp2"
            DeleteOnTermination: true
            VolumeSize: 8
      ImageId: ami-01fee56b22f308154
      InstanceType: t2.micro
      KeyName: EC2-KP
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${EnvironmentName}-PUB1-SN"
          GroupSet: 
            - !Ref JenkinsSG
      Tags: 
        - Key: Name 
          Value: Jenkins Host
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo yum update -y
          sudo yum install java-1.8.0 -y
          sudo yum remove java-1.7.0-openjdk -y
          sudo yum install git -y
          sudo yum install tidy -y
          sudo yum install docker -y
          sudo service docker start
          echo "installing kubectl"
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          echo "install jenkins"
          sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
          sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
          sudo yum install jenkins -y
          sudo usermod -a -G docker jenkins
          sudo service jenkins start 
          sudo chkconfig --add jenkins
          sudo chkconfig jenkins on
          sudo service jenkins status 
          